### ISSUE TITLE
Coordinates causing my website to crash when I update

### ISSUE THREAD

**Issue by mpetter** [StupidStudio/acf-coordinates#1]
I cannot update Advanced Custom Fields, without this plugin crashes my site.
When I disable the coordinates plugin I have no problems updating ACF. But when activating coordinates again my site crashes.

PHP Fatal error:  Access level to acf_field_coordinates::$defaults must be public (as in class acf_field) in /wp-root/wp-content/plugins/acf-coordinates/acf-coordinates.php on line 44

acf_field_coordinates_plugin->register_fields() /wp-root/wp-includes/plugin.php:406

**Comment by ChrisBuchholz** [comment]
I have committed a fix for it[1](https://github.com/StupidStudio/acf-coordinates/commit/addd66f9ab912a31c4d43fc33fe8649ee060ca5e). This seems to solve the problem.

I am closing this issue.
