### ISSUE TITLE
Can't update location

### ISSUE THREAD

**Issue by mpetter** [StupidStudio/acf-coordinates#2]
I can not update the map by adding a new address, only by dragging the marker.

**Comment by bitnissen** [comment]
It works, but requires you to push "Enter" after entering an address.

A possible solution could be to add an "Update map"-button, which essentially is a `type="submit"`-button.

An even sexier solution would be to detect change in the field and, when hitting publish on the post, update the Google Map. I don't know if this is easily done, overwriting the behaviour of the post publishing.

**Comment by ChrisBuchholz** [comment]
The plugin listens for a keypress on the return key, so if you type the
address and press return it should update. If it doesn't, it's broken.

It works for me with the current HEAD. Lemme know if it doesn't for you.

torsdag den 5. september 2013 skrev Michael Petter :

> I can not update the map by adding a new address, only by dragging the
> marker.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StupidStudio/acf-coordinates/issues/2
> .

## 

## 

Christoffer Buchholz

**Comment by mpetter** [comment]
Agree with @mortenskyt A "update map" button would in my case solve any misunderstanding. But @ChrisBuchholz your right, i just didn't know that i a return was required. Case closed.

**Comment by ChrisBuchholz** [comment]
Exactly @mortenskyt.

I dunno what the best solution would be. Just looking for change on the input or using a submit button? Dunno but both would surely work although I think I like the button the least.

Perhaps just looking for change on the input, setting a timeout of about 200 ms every time you type something and clearing the old timeout. When you haven't typed for 200 ms, the timeouts callback is fired and the location is updated?

**Comment by bitnissen** [comment]
Automatically updating based on a time out, has the disadvantage, that it will change the text-version of the location, if you decided to move the pin manually.

Otherwise, a simple solution for starters, would be adding a text above/below the field stating something like "To update the field according to the entered address, hit enter". The issue, as I see it, is that users may not hit Enter instinctively. A note may resolve this issue completely - no extra magic timeouts, widgets etc.

Sounds good?

**Comment by ChrisBuchholz** [comment]
Yeah sure.

I think we actually had the same talk when we initially created the plugin
:D

torsdag den 5. september 2013 skrev Morten Skyt Eriksen :

> Automatically updating based on a time out, has the disadvantage, that it
> will change the text-version of the location, if you decided to move the
> pin manually.
> 
> Otherwise, a simple solution for starters, would be adding a text
> above/below the field stating something like "To update the field according
> to the entered address, hit enter". The issue, as I see it, is that users
> may not hit Enter instinctively. A note may resolve this issue completely -
> no extra magic timeouts, widgets etc.
> 
> Sounds good?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/StupidStudio/acf-coordinates/issues/2#issuecomment-23859030
> .

## 

## 

Christoffer Buchholz
